language:
  - c
  - cpp
  - go
  - d

addons:
  apt:
    packages:
    - libsdl2-2.0-0
    - libsdl2-dev
    - libsdl2-gfx-dev
    - libsdl2-image-2.0-0
    - libsdl2-image-dev
    - libsdl2-mixer-2.0-0
    - libsdl2-net-2.0-0
    - libsdl2-net-dev
    - libsdl2-ttf-2.0-0
    - libsdl2-ttf-dev
    - cmake
    - ninja-build

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

script:
  - make -C c11
  - make -C c++98
  - make -C c++11
  - pushd go
  - go get -d -v
  - go build
  - go test
  - popd
  - mkdir -p build
  - cd build && cmake -G Ninja -- ../c++17-cmake && ninja
